# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170420_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmessage',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Topic'),
        ),
    ]
