# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170420_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterModelOptions(
            name='topicmessage',
            options={'ordering': ['-published_date']},
        ),
    ]
