# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20170420_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmessage',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
