# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignuser',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
