# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20170415_1759'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='campaign',
            managers=[
            ],
        ),
    ]
