# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 18:09
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20170415_1804'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='campaign',
            managers=[
                ('dm', django.db.models.manager.Manager()),
            ],
        ),
    ]
