# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['date']},
        ),
    ]
