# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 21:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_sessionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionuser',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Session'),
        ),
        migrations.AlterField(
            model_name='sessionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
