# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0015_auto_20170418_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
