# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0017_auto_20170421_2336'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='campaignuser',
            managers=[
            ],
        ),
    ]
