# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0020_auto_20170424_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houserules',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
