# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0026_gamereport_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereport',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign'),
        ),
    ]
